const dummyData = [
  {
    id: 1,
    name: "Recipe 1",
    ingredients: "Ingredient A, Ingredient B, Ingredient C",
    experience_level: ["BEGINNER"],
    meal_type: ["BREAKFAST"],
    equipment_needed: ["NONE_EQUIPMENT"],
    allergen: ["NONE_ALLERGEN"],
    time_commitment: ["UNDER30"],
    instructions: "No instructions, sorry",
  },
  {
    id: 2,
    name: "Recipe 2",
    ingredients: "Ingredient X, Ingredient Y, Ingredient Z",
    experience_level: ["INTERMEDIATE"],
    meal_type: ["LUNCH"],
    equipment_needed: ["POT"],
    allergen: ["PEANUT"],
    time_commitment: ["UNDER60"],
    instructions: "No instructions, sorry",
  },
  {
    id: 3,
    name: "Recipe 3",
    ingredients: "Ingredient M, Ingredient N, Ingredient O",
    experience_level: ["ADVANCED"],
    meal_type: ["DINNER"],
    equipment_needed: ["OVEN"],
    allergen: ["SOY"],
    time_commitment: ["OVER60"],
    instructions: "No instructions, sorry",
  },
  {
    id: 4,
    name: "Recipe 4",
    ingredients: "Ingredient P, Ingredient Q, Ingredient R",
    experience_level: ["BEGINNER", "INTERMEDIATE"],
    meal_type: ["SNACK"],
    equipment_needed: ["MICROWAVE"],
    allergen: ["NONE_ALLERGEN"],
    time_commitment: ["UNDER30"],
    instructions: "No instructions, sorry",
  },
  {
    id: 5,
    name: "Recipe 5",
    ingredients: "Ingredient J, Ingredient K, Ingredient L",
    experience_level: ["ADVANCED"],
    meal_type: ["BREAKFAST", "LUNCH"],
    equipment_needed: ["BLENDER"],
    allergen: ["EGG"],
    time_commitment: ["UNDER30"],
    instructions: "No instructions, sorry",
  },
  {
    id: 6,
    name: "Recipe 6",
    ingredients: "Ingredient D, Ingredient E, Ingredient F",
    experience_level: ["BEGINNER"],
    meal_type: ["DINNER"],
    equipment_needed: ["STOVE"],
    allergen: ["MILK"],
    time_commitment: ["UNDER30"],
    instructions: "No instructions, sorry",
  },
  {
    id: 7,
    name: "Recipe 7",
    ingredients: "Ingredient G, Ingredient H, Ingredient I",
    experience_level: ["INTERMEDIATE"],
    meal_type: ["SNACK"],
    equipment_needed: ["NONE_EQUIPMENT"],
    allergen: ["WHEAT"],
    time_commitment: ["UNDER30"],
    instructions: "No instructions, sorry",
  },
  {
    id: 8,
    name: "Recipe 8",
    ingredients: "Ingredient U, Ingredient V, Ingredient W",
    experience_level: ["ADVANCED"],
    meal_type: ["BREAKFAST", "LUNCH", "DINNER"],
    equipment_needed: ["GRILL"],
    allergen: ["FISH"],
    time_commitment: ["OVER60"],
    instructions: "No instructions, sorry",
  },
  {
    id: 9,
    name: "Recipe 9",
    ingredients: "Ingredient S, Ingredient T, Ingredient X",
    experience_level: ["BEGINNER", "ADVANCED"],
    meal_type: ["DESSERT"],
    equipment_needed: ["MIXER"],
    allergen: ["NUT"],
    time_commitment: ["UNDER30"],
    instructions: "No instructions, sorry",
  },
  {
    id: 10,
    name: "Recipe 10",
    ingredients: "Ingredient Y, Ingredient Z, Ingredient A",
    experience_level: ["INTERMEDIATE"],
    meal_type: ["SNACK"],
    equipment_needed: ["NONE_EQUIPMENT"],
    allergen: ["NONE_ALLERGEN"],
    time_commitment: ["UNDER30"],
    instructions: "No instructions, sorry",
  },
];
